//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseDescriptionTool.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatabaseDescriptionTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap arrow_refresh {
            get {
                object obj = ResourceManager.GetObject("arrow_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap book {
            get {
                object obj = ResourceManager.GetObject("book", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap book_add {
            get {
                object obj = ResourceManager.GetObject("book_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap book_delete {
            get {
                object obj = ResourceManager.GetObject("book_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap book_edit {
            get {
                object obj = ResourceManager.GetObject("book_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap book_go {
            get {
                object obj = ResourceManager.GetObject("book_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap book_goback {
            get {
                object obj = ResourceManager.GetObject("book_goback", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap bullet_green {
            get {
                object obj = ResourceManager.GetObject("bullet_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap bullet_orange {
            get {
                object obj = ResourceManager.GetObject("bullet_orange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap database {
            get {
                object obj = ResourceManager.GetObject("database", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap database_key {
            get {
                object obj = ResourceManager.GetObject("database_key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap disk {
            get {
                object obj = ResourceManager.GetObject("disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap find_small {
            get {
                object obj = ResourceManager.GetObject("find_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap font {
            get {
                object obj = ResourceManager.GetObject("font", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 select e.name, count(e.name) [count]
        ///from sys.extended_properties e
        ///where isnull(e.name, &apos;&apos;) != &apos;microsoft_database_tools_support&apos; and e.value != &apos;&apos;
        ///group by e.name
        ///order by e.name
        /// 的本地化字符串。
        /// </summary>
        internal static string GetDescriptionFields {
            get {
                return ResourceManager.GetString("GetDescriptionFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select u.Level1Type, u.Level1Name, u.Level2Type, u.Level2Name, u.DatabaseFieldName
        ///from
        ///(
        ///	-- All Level1
        ///	select u1.Level1Type, u1.Level1Name, u1.Level2Type, u1.Level2Name, u1.Level1DatabaseFieldName DatabaseFieldName
        ///	from
        ///	(
        ///		select &apos;Table&apos; Level1Type, t.name Level1Name, &apos;&apos; Level2Type, &apos;&apos; Level2Name, e.name Level1DatabaseFieldName
        ///		from sys.tables t
        ///		inner join sys.extended_properties e on e.major_id = t.object_id and minor_id = 0 and e.class = 1
        ///		where schema_name(t.schema_id) = &apos;{0}&apos; and i [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string GetDescriptionsToDelete {
            get {
                return ResourceManager.GetString("GetDescriptionsToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select s.id
        ///from
        ///(
        ///	select row_number () over (order by u.Level1TypeSortBy, u.Level1Name, u.Level2TypeSortBy, u.Level2NameSortBy) id, u.Level1Type, u.Level1Name, isnull(u.Level2Type, &apos;&apos;) Level2Type, isnull(u.Level2Name, &apos;&apos;) Level2Name
        ///	from
        ///	(
        ///		select &apos;Table&apos; Level1Type, t.name Level1Name, l2.Level2Type, l2.Level2Name, 1 Level1TypeSortBy, l2.Level2TypeSortBy, l2.Level2NameSortBy
        ///		from sys.tables t
        ///		left join
        ///		(
        ///			select &apos;Column&apos; Level2Type, c.name Level2Name, 2 Level2TypeSortBy, row_number()  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string GetIdFromName {
            get {
                return ResourceManager.GetString("GetIdFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select row_number () over (order by u.Level1TypeSortBy, u.Level1Name, u.Level2TypeSortBy, u.Level2NameSortBy) id, u.Level1Type, u.Level1Name, isnull(u.Level2Type, &apos;&apos;) Level2Type, isnull(u.Level2Name, &apos;&apos;) Level2Name, u.Level1TypeSortBy, u.Level2TypeSortBy, u.Level2NameSortBy
        ///into #names
        ///from
        ///(
        ///	select &apos;Table&apos; Level1Type, t.name Level1Name, l2.Level2Type, l2.Level2Name, 1 Level1TypeSortBy, l2.Level2TypeSortBy, l2.Level2NameSortBy
        ///	from sys.tables t
        ///	left join
        ///	(
        ///		select &apos;Column&apos; Level2Type, c.name Le [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string GetMatches {
            get {
                return ResourceManager.GetString("GetMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 declare @sql nvarchar(max)
        ///
        ///select @sql = &apos;select distinct t.name
        ///from
        ///(
        ///&apos; + stuff((select &apos;
        ///
        ///	union all
        ///
        ///	select s.name collate database_default name
        ///	from &apos; + quotename(d.name) + &apos;.sys.schemas s&apos;
        ///from sys.databases d
        ///where d.name not in (&apos;master&apos;, &apos;tempdb&apos;, &apos;model&apos;, &apos;msdb&apos;)
        ///and d.state_desc = &apos;ONLINE&apos;
        ///for xml path(&apos;&apos;), type).value(&apos;.&apos;, &apos;nvarchar(max)&apos;), 1, 18, &apos;&apos;)
        ///
        ///set @sql = @sql + &apos;
        ///) t
        ///order by t.name
        ///&apos;
        ///
        ///exec (@sql)
        /// 的本地化字符串。
        /// </summary>
        internal static string GetSchemas {
            get {
                return ResourceManager.GetString("GetSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] ICSharpCode_TextEditor {
            get {
                object obj = ResourceManager.GetObject("ICSharpCode_TextEditor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Microsoft_SqlServer_ConnectionInfo {
            get {
                object obj = ResourceManager.GetObject("Microsoft_SqlServer_ConnectionInfo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Microsoft_SqlServer_Management_Sdk_Sfc {
            get {
                object obj = ResourceManager.GetObject("Microsoft_SqlServer_Management_Sdk_Sfc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Microsoft_SqlServer_Smo {
            get {
                object obj = ResourceManager.GetObject("Microsoft_SqlServer_Smo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Microsoft_SqlServer_SqlClrProvider {
            get {
                object obj = ResourceManager.GetObject("Microsoft_SqlServer_SqlClrProvider", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Microsoft_SqlServer_SqlEnum {
            get {
                object obj = ResourceManager.GetObject("Microsoft_SqlServer_SqlEnum", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap server_database {
            get {
                object obj = ResourceManager.GetObject("server_database", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap update {
            get {
                object obj = ResourceManager.GetObject("update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
